# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/project-chip/chip-build:22
        volumes:
            - "/tmp/log_output:/tmp/test_logs"
        options: --privileged -v /lib/modules:/lib/modules --sysctl "net.ipv6.conf.all.disable_ipv6=0
            net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1"
    steps:
      - uses: actions/checkout@v3

      - name: Hello World
        run: echo Hello, world!
      - name: ls
        run: ls /opt

      - name: modprobe
        run: modprobe mac80211_hwsim radios=2

      - name: ip a
        run: ip a

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
